### ISSUE TITLE
Eggtab prevent enchants from showing in REI

### ISSUE THREAD

**Issue by dandin87** [florensie/eggtab-fabric#15]
All of Fabric 5 modpack
With Eggtab enabled
![2022-06-08_11 33 18](https://user-images.githubusercontent.com/9329117/172691418-01cca4dc-b6be-48a6-8c0f-f82fa83f4e55.png)

With Eggtab disabled
![2022-06-08_11 29 57](https://user-images.githubusercontent.com/9329117/172691483-85848b51-a1b6-4362-a6a9-91cf7330312a.png)

**Comment by florensie** [comment]
This happens with the creative items tab enabled. Further investigation necessary, you can disable that tab in the config screen/file in the meantime.
