### ISSUE TITLE
Feature Request: More Tabs

### ISSUE THREAD

**Issue by Boobies** [florensie/eggtab-fabric#6]
Would be nice if you included tabs for potions and arrows. Those are kind of messy in the Creative inventory.

**Comment by ghost** [comment]
+ Music tab <3

**Comment by Boobies** [comment]
Idk about the music tab but another tab that would be nice would be a tab to add all the things that are only available through commands: command blocks, sculk sensors, void blocks, and so on. There is a mod that does this that has not been updated for 1.18 and Egg Tab seems like the perfect place for this functionality.

https://www.curseforge.com/minecraft/mc-mods/command-creative-tab
