### ISSUE TITLE
Complex problem with eggtab.toml file

### ISSUE THREAD

**Issue by Felix14-v2** [florensie/eggtab-fabric#7]
After some use, EggTab became unconfigurable, and also broke the work of the Dark Loading Screen mod (Mojang logo disappeared). The problem was the eggtab.toml file. Removing it fixed the problem.

Damaged settings file
[eggtab.zip](https://github.com/florensie/eggtab-fabric/files/6239306/eggtab.zip)

Dark Loading Screen
![image](https://user-images.githubusercontent.com/75726196/113207227-09ea9a00-9279-11eb-9387-2006ac7336ce.png)

Missing Settings button
![image](https://user-images.githubusercontent.com/75726196/113207213-05be7c80-9279-11eb-8f88-dcb2626613ce.png)

**Comment by florensie** [comment]
Probably the result of the old AutoConfig api. Will have to update that, thanks for reporting this to me.

**Comment by RooftopJoe** [comment]
@Felix14-v2 Does this still happen for the build found here: https://github.com/florensie/eggtab-fabric/suites/5761945067/artifacts/191581951 ? I would expect not given the recent switch to Cloth Config but if you could test it, that would be great.

**Comment by Felix14-v2** [comment]
I tested it for many launches/settings changes, no problems have occurred, thanks! If the problem comes up again, I'll let you know.

**Comment by florensie** [comment]
Thanks for checking.
